images:
  - location: ~/scratch/VMs/disk.qcow2

cpus: 6
memory: 16GiB
disk: 30GiB

containerd:
  system: false
  user: false

mountType: virtiofs
mounts:
  - location: "~/scratch/output"
    mountPoint: "/output"
    writable: true

provision: []
