#!/bin/bash

sudo podman run --privileged \
   -v ~/scratch/output:/output \
   -v ./blueprints:/config \
   ghcr.io/osbuild/image-builder-cli:latest \
   build \
   --distro fedora-43 \
   --blueprint /config/fedora.json \
   --extra-repo https://download.copr.fedorainfracloud.org/results/atim/lazygit/fedora-43-aarch64/ \
   --extra-repo https://download.copr.fedorainfracloud.org/results/atim/starship/fedora-43-aarch64/ \
   qcow2
